# Generated by Django 5.2.5 on 2025-08-17 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_patientdischarge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientDischarge',
        ),
    ]
