# Generated by Django 5.2.5 on 2025-08-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_patientdischarge'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
