# Generated by Django 5.2.5 on 2025-08-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='Staff_profiles/'),
        ),
    ]
