# Generated by Django 5.2.5 on 2025-08-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_staffprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='current_status',
            field=models.CharField(choices=[('apporved', 'Approved'), ('panding', 'Panding'), ('cancel', 'Cancel')], default='panding', max_length=50),
        ),
    ]
