# Generated by Django 5.2.5 on 2025-08-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_doctorprofile_current_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='current_status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_status',
            field=models.CharField(choices=[('apporved', 'Approved'), ('panding', 'Panding'), ('cancel', 'Cancel')], default='panding', max_length=50),
        ),
    ]
