# Generated by Django 5.2.5 on 2025-08-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_patientprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='availability_status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='consultation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='experience',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
