# Generated by Django 5.2.5 on 2025-08-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_doctorprofile_availability_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='availability_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='status',
            field=models.CharField(choices=[('Outpatient', 'Outpatient'), ('Inpatient', 'Inpatient'), ('Discharged', 'Discharged')], default='Outpatient', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
