# Generated by Django 5.2.5 on 2025-08-28 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_doctorprofile_availability_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='doctor_assigned',
        ),
    ]
