# Generated by Django 5.2.5 on 2025-08-19 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_patientdischarge'),
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdiagnosis',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.patientprofile'),
        ),
    ]
