# Generated by Django 5.2.5 on 2025-08-19 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_patientdiagnosis_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdiagnosis',
            name='patient',
        ),
    ]
