# Generated by Django 5.2.5 on 2025-08-18 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_patientdischarge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdischarge',
            name='admission_date',
        ),
        migrations.RemoveField(
            model_name='patientdischarge',
            name='discharge_date',
        ),
        migrations.RemoveField(
            model_name='patientdischarge',
            name='total_bill',
        ),
    ]
