# Generated by Django 5.2.5 on 2025-08-23 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_doctorprofile_bio'),
        ('appointment', '0003_remove_patientdiagnosis_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billDate', models.DateTimeField(auto_now_add=True)),
                ('consultationFee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('medicineCharges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('testCharges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('roomCharges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('otherCharges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('totalAmount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('paymentStatus', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patientprofile')),
            ],
        ),
    ]
