# Generated by Django 5.2.5 on 2025-08-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_patientdischarge'),
        ('appointment', '0003_remove_patientdischarge_admission_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientDischarge',
            new_name='PatientDiagnosis',
        ),
    ]
