# Generated by Django 5.2.5 on 2025-08-23 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='roomCharges',
        ),
    ]
