# Generated by Django 5.2.5 on 2025-08-18 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_rename_patientdischarge_patientdiagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdiagnosis',
            name='appointment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment'),
        ),
    ]
