# Generated by Django 5.2.5 on 2025-08-19 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_patientdiagnosis_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdiagnosis',
            name='patient',
        ),
    ]
