# Generated by Django 5.2.5 on 2025-08-19 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_remove_patientdiagnosis_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdiagnosis',
            name='appointment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='appointment.appointment'),
        ),
    ]
