# Generated by Django 5.2.5 on 2025-08-19 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_alter_patientdiagnosis_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdiagnosis',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='appointment.appointment'),
        ),
    ]
